<?php

header('content-type:application/json;charset=utf-8');

$experts = [
    "hasError"  => false,
    "code"      => "1",
    "map"       => null,
    "returnUrl" => null,
    "message"   => null,
    "data"      => [
        [
            "id"                      => "125618865453990000",
            "sex"                     => "男",
            "name"                    => "张义",
            "photo"                   => "https=>//kano.guahao.cn/aqc2674956_image140.jpg?timestamp=1469584360808",
            "consult"                 => 2,
            "feature"                 => "脑肿瘤的手术治疗。主攻胶质瘤。经长期从事脑肿瘤和...",
            "wzDiagnosis"             => 1,
            "isImageText"             => 1,
            "hospitalName"            => "复旦大学附属华山医院,复旦大学附属华山医院西院",
            "commentScore"            => 9.6,
            "multiPractice"           => "1",
            "titleTypeText"           => "主任医师",
            "totalConsultCount"       => 952,
            "volunteerRemainCount"    => -1,
            "expertGroupIdList"       => ["8046"],
            "expertHospName"          => "复旦大学附属华山医院",
            "expertHospDeptName"      => "神经外科",
            "searchDoctorConsultlist" => [
                [
                    "doctorConsultType"          => "0",
                    "doctorConsultPrice"         => "200",
                    "doctorConsultStatus"        => "1",
                    "doctorConsultOriginalPrice" => null,
                    "doctorConsultActivityIcon"  => null,
                    "scheduleId"                 => 128968860,
                ],
                [
                    "doctorConsultType"          => "3",
                    "doctorConsultPrice"         => "160",
                    "doctorConsultStatus"        => "1",
                    "doctorConsultOriginalPrice" => null,
                    "doctorConsultActivityIcon"  => null,
                    "scheduleId"                 => -1,
                ],
            ],
        ],
        [
            "id"                      => "91341c2a-8631-45bc-a052-7e85bf004b2e000",
            "sex"                     => "男",
            "name"                    => "尚爱加",
            "photo"                   => "https=>//kano.guahao.cn/ROy17390757_image140.jpg?timestamp=1504078899886",
            "consult"                 => 2,
            "feature"                 => "椎管内肿瘤（脊髓肿瘤），颈椎病，腰间盘突出，小脑...",
            "wzDiagnosis"             => 2,
            "isImageText"             => 1,
            "hospitalName"            => "中国人民解放军总医院301医院",
            "commentScore"            => 9.6,
            "multiPractice"           => "0",
            "titleTypeText"           => "主任医师",
            "totalConsultCount"       => 242,
            "volunteerRemainCount"    => -1,
            "expertGroupIdList"       => ["1985"],
            "expertHospName"          => "中国人民解放军总医院301医...",
            "expertHospDeptName"      => "神经外科",
            "searchDoctorConsultlist" => [
                [
                    "doctorConsultType"          => "0",
                    "doctorConsultPrice"         => "100",
                    "doctorConsultStatus"        => "1",
                    "doctorConsultOriginalPrice" => null,
                    "doctorConsultActivityIcon"  => null,
                    "scheduleId"                 => 128974413,
                ],
                [
                    "doctorConsultType"          => "3",
                    "doctorConsultPrice"         => "0",
                    "doctorConsultStatus"        => "0",
                    "doctorConsultOriginalPrice" => null,
                    "doctorConsultActivityIcon"  => null,
                    "scheduleId"                 => -1,
                ],
            ],
        ],
        [
            "id"                      => "e7e4897f-c2e2-451e-907b-0d4d776c7592000",
            "sex"                     => "男",
            "name"                    => "凌至培",
            "photo"                   => "https=>//kano.guahao.cn/Csq2704641_image140.jpg?timestamp=1504082853127",
            "consult"                 => 2,
            "feature"                 => "癫痫、帕金森病、震颤、肌张力障碍、斜颈、梅杰、抽...",
            "wzDiagnosis"             => 1,
            "isImageText"             => 1,
            "hospitalName"            => "中国人民解放军总医院301医院",
            "commentScore"            => 9.0,
            "multiPractice"           => "0",
            "titleTypeText"           => "主任医师",
            "totalConsultCount"       => 56,
            "volunteerRemainCount"    => -1,
            "expertGroupIdList"       => ["7705"],
            "expertHospName"          => "中国人民解放军总医院301医...",
            "expertHospDeptName"      => "神经外科",
            "searchDoctorConsultlist" => [
                [
                    "doctorConsultType"          => "0",
                    "doctorConsultPrice"         => "200",
                    "doctorConsultStatus"        => "1",
                    "doctorConsultOriginalPrice" => null,
                    "doctorConsultActivityIcon"  => null,
                    "scheduleId"                 => 129018191,
                ],
                [
                    "doctorConsultType"          => "3",
                    "doctorConsultPrice"         => "500",
                    "doctorConsultStatus"        => "3",
                    "doctorConsultOriginalPrice" => null,
                    "doctorConsultActivityIcon"  => null,
                    "scheduleId"                 => -1,
                ],
            ],
        ],
        [
            "id"                      => "dbf3be70-33d3-40e7-a2cc-f9abe60ce1d7000",
            "sex"                     => "男",
            "name"                    => "任善成",
            "photo"                   => "https=>//kano.guahao.cn/YYJ49044345_image140.jpg?timestamp=1538286155883",
            "consult"                 => 2,
            "feature"                 => "1，前列腺癌微创手术（腹腔镜，达芬奇机器人手术）...",
            "wzDiagnosis"             => 1,
            "isImageText"             => 1,
            "hospitalName"            => "上海长海医院,上海国际医学中心",
            "commentScore"            => 9.8,
            "multiPractice"           => "1",
            "titleTypeText"           => "副主任医师",
            "totalConsultCount"       => 520,
            "volunteerRemainCount"    => -1,
            "expertGroupIdList"       => ["7744"],
            "expertHospName"          => "上海长海医院",
            "expertHospDeptName"      => "泌尿外科",
            "searchDoctorConsultlist" => [
                [
                    "doctorConsultType"          => "0",
                    "doctorConsultPrice"         => "100",
                    "doctorConsultStatus"        => "1",
                    "doctorConsultOriginalPrice" => null,
                    "doctorConsultActivityIcon"  => null,
                    "scheduleId"                 => 128990583,
                ],
                [
                    "doctorConsultType"          => "3",
                    "doctorConsultPrice"         => "600",
                    "doctorConsultStatus"        => "3",
                    "doctorConsultOriginalPrice" => null,
                    "doctorConsultActivityIcon"  => null,
                    "scheduleId"                 => -1,
                ],
            ],
        ],
        [
            "id"                      => "609c8a02-3f9d-4aed-a221-811e22ab6a60000",
            "sex"                     => "男",
            "name"                    => "陈华",
            "photo"                   => "https=>//kano.guahao.cn/thA2684725_image140.jpg?timestamp=1504077357702",
            "consult"                 => 2,
            "feature"                 => "关节畸形、陈旧骨折，骨折微创手术，神经/肌腱功能...",
            "wzDiagnosis"             => 1,
            "isImageText"             => 1,
            "hospitalName"            => "中国人民解放军总医院301医院",
            "commentScore"            => 9.4,
            "multiPractice"           => "0",
            "titleTypeText"           => "副主任医师",
            "totalConsultCount"       => 126,
            "volunteerRemainCount"    => -1,
            "expertGroupIdList"       => ["7482"],
            "expertHospName"          => "中国人民解放军总医院301医...",
            "expertHospDeptName"      => "骨科",
            "searchDoctorConsultlist" => [
                [
                    "doctorConsultType"          => "0",
                    "doctorConsultPrice"         => "300",
                    "doctorConsultStatus"        => "1",
                    "doctorConsultOriginalPrice" => null,
                    "doctorConsultActivityIcon"  => null,
                    "scheduleId"                 => 128996058,
                ],
                [
                    "doctorConsultType"          => "3",
                    "doctorConsultPrice"         => "300",
                    "doctorConsultStatus"        => "1",
                    "doctorConsultOriginalPrice" => null,
                    "doctorConsultActivityIcon"  => null,
                    "scheduleId"                 => -1,
                ],
            ],
        ],
        [
            "id"                      => "e4831c27-f7b8-4c73-9b3f-d740cb6617ae000",
            "sex"                     => "男",
            "name"                    => "张立海",
            "photo"                   => "https=>//kano.guahao.cn/fna2704268_image140.jpg?timestamp=1474876779016",
            "consult"                 => 2,
            "feature"                 => "陈旧骨折、骨不连的修复与重建，骨盆髋臼骨折、骨质...",
            "wzDiagnosis"             => 1,
            "isImageText"             => 1,
            "hospitalName"            => "中国人民解放军总医院301医院",
            "commentScore"            => 9.3,
            "multiPractice"           => "0",
            "titleTypeText"           => "副主任医师",
            "totalConsultCount"       => 335,
            "volunteerRemainCount"    => -1,
            "expertGroupIdList"       => ["7700"],
            "expertHospName"          => "中国人民解放军总医院301医...",
            "expertHospDeptName"      => "骨科",
            "searchDoctorConsultlist" => [
                [
                    "doctorConsultType"          => "0",
                    "doctorConsultPrice"         => "100",
                    "doctorConsultStatus"        => "1",
                    "doctorConsultOriginalPrice" => null,
                    "doctorConsultActivityIcon"  => null,
                    "scheduleId"                 => 128983717,
                ],
                [
                    "doctorConsultType"          => "3",
                    "doctorConsultPrice"         => "200",
                    "doctorConsultStatus"        => "1",
                    "doctorConsultOriginalPrice" => null,
                    "doctorConsultActivityIcon"  => null,
                    "scheduleId"                 => -1,
                ],
            ],
        ],
        [
            "id"                      => "125618827489778000",
            "sex"                     => "男",
            "name"                    => "徐斌",
            "photo"                   => "https=>//kano.guahao.cn/eD52674942_image140.jpg?timestamp=1524820671698",
            "consult"                 => 2,
            "feature"                 => "脑、脊髓的血管性疾病。包括烟雾病、动脉瘤、脑血管...",
            "wzDiagnosis"             => 1,
            "isImageText"             => 1,
            "hospitalName"            => "复旦大学附属华山医院,复旦大学附属华山医院东院",
            "commentScore"            => 9.5,
            "multiPractice"           => "1",
            "titleTypeText"           => "主任医师",
            "totalConsultCount"       => 806,
            "volunteerRemainCount"    => -1,
            "expertGroupIdList"       => [],
            "expertHospName"          => "复旦大学附属华山医院",
            "expertHospDeptName"      => "神经外科",
            "searchDoctorConsultlist" => [
                [
                    "doctorConsultType"          => "0",
                    "doctorConsultPrice"         => "300",
                    "doctorConsultStatus"        => "1",
                    "doctorConsultOriginalPrice" => null,
                    "doctorConsultActivityIcon"  => null,
                    "scheduleId"                 => 128968877,
                ],
                [
                    "doctorConsultType"          => "3",
                    "doctorConsultPrice"         => "500",
                    "doctorConsultStatus"        => "3",
                    "doctorConsultOriginalPrice" => null,
                    "doctorConsultActivityIcon"  => null,
                    "scheduleId"                 => -1,
                ],
            ],
        ],
    ],
];

echo json_encode($experts);
